trigger:
  branches:
    include:
      - master
  paths:
    include:
    - papillon/*

pr:
  paths:
    include:
    - papillon/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Bonjour!
  displayName: 'Bonjour'