trigger:
  branches:
    include:
      - master
  paths:
    include: 
    - mariposa/*

pr:
  paths:
    include: 
    - mariposa/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo ¡Hola!
  displayName: 'Hola'