trigger:
  branches:
    include:
      - master
  paths:
    include:
    - borboleta/*
    
pr:
  paths:
    include:
    - borboleta/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Olá!
  displayName: 'Olá'